### ISSUE TITLE
an error when train

### ISSUE THREAD

**Issue by zhaobingbingbing** [SunnerLi/GANomaly2D#1]
Hi,
I face an error when I want to run the train.py,
"Traceback (most recent call last):
  File "train.py", line 66, in <module>
    train(args)
  File "train.py", line 35, in train
    sunnerTransforms.Normalize(),
TypeError: __init__() got an unexpected keyword argument 'transform'
"
My enviorment is pytorch 1.0,torchvison 0.21, and I install Torchvision_sunner you mentioned.
I think this error may be caused by the version of torchvision, and I have upgrade or degrade the version , but it doesn't work.

**Comment by SunnerLi** [comment]
Hi @zhaobingbingbing ,
Very delight that you can reply the bug!
I have already fixed recently, and you can try again.
You can use the latest version of `Torchvision_sunner` package to do the training or inference.
If you have any problem, feel free to re-open the issue.
